### ISSUE TITLE
problème avec composer

### ISSUE THREAD

**Issue by Stoakes** [flef/Incipio#142]
A ce jour (07/06/2015), composer n'arrive plus à trouver une solution aux dépendances.

$:  composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - stof/doctrine-extensions-bundle dev-master requires gedmo/doctrine-extensions ~2.3.1 -> no matching package found.
    - stof/doctrine-extensions-bundle dev-master requires gedmo/doctrine-extensions ~2.3.1 -> no matching package found.
    - Installation request for stof/doctrine-extensions-bundle dev-master -> satisfiable by stof/doctrine-extensions-bundle[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by theofidry** [comment]
Salut @Stoakes.

Le projet va énormément bouger sous peu et est actuellement en dev sur [CDJE/Incipio](https://github.com/CDJE/Incipio/tree/1.0), qui va bientôt passer sous le namespace `in6pio`.

Pour le problème de résolution de dépendances cela vient du fait de l'absence de `composer.lock` qu'a omis de commit @flef. Je remet ça sur la branche que je t'ai linké dans la journée.
